### ISSUE TITLE
permissions for protected main branch.

### ISSUE THREAD

**Issue by willscott** [ipfs/github-mgmt#52]
I'm trying to merge an approved PR in the `specs` repo, but do not appear to have permissions to do so: https://github.com/ipfs/specs/pull/312

It is not clear to me what i should be proposing to change with the permissions definition here to fix that:
https://github.com/ipfs/github-mgmt/blob/master/github/ipfs.yml#L4139-L4165

* `- Specs Stewards` get push access, as do I, which i think is enough to make the PR
* the branch protection is just that it is protected:
```
branch_protection:
      main: {}
```

the github docs I can find just say: "By default, each branch protection rule disables force pushes to the matching branches and prevents the matching branches from being deleted." which does imply why an approved PR can't be merged.

I can't see settings on the repo so don't know if settings for what the branch protection is structured as match or are more restrictive than what's listed in this repo.

**Comment by galargh** [comment]
Hey, the reason why we don't have any properties listed currently for `branch_protection` rules is because we ignore all of them in https://github.com/ipfs/github-mgmt/blob/59765eec078f9019eb4e4ce69c0253a3f1af3341/terraform/resources_override.tf#L27-L41

To start managing `branch_protection` properties through GitHub Management, we can draw inspiration from this guide: https://github.com/ipfs/github-mgmt/blob/47ac0c250b98b0cdeea7dc6af5454f8c16ba4fa4/docs/HOWTOS.md#stop-managing-a-resource-attribute-through-github-management 

I created a PR which will enable managing `branch_protection` props through GitHub Management here: https://github.com/ipfs/github-mgmt/pull/66

**Comment by galargh** [comment]
`branch_protection` props are now correctly reflected in `ipfs.yml`. See https://github.com/ipfs/github-mgmt/blob/05f599d6fa8a4931713b8ed68e981f6c3bc85b6f/github/ipfs.yml#L4912-L4927

As you can see, the `push_restrictions` field is not too useful at the moment as it is a list of IDs. I created an issue to make it more user friendly - https://github.com/protocol/github-mgmt-template/issues/74

**Comment by galargh** [comment]
I'm going to close this issue now since we now have more complete info on configuration of protected branches in github management. Feel free to reopen if it doesn't fully resolve the original issue.
